version: "3.2"
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge