spring:
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 10s
          max-attempts: 2
          max-interval: 15s
          multiplier: 1
        missing-queues-fatal: false